title: Parvathi Pradeep
logo: /assets/img/parvathi new.jpg
description: I’m Parvathi Pradeep, a Computer Science undergraduate at Lovely Professional University, graduating in 2026. I’m passionate about solving problems, adapting to challenges, and expressing creativity through art and collaboration.
theme: jekyll-theme-minimal
